### ISSUE TITLE
to do da aggiungere nelle crud di games

### ISSUE THREAD

**Issue by Sebastian-ivaniczki** [Sebastian-ivaniczki/laravel-vue-comp#4]
1. da aggiungere nel form prezzo vendita con 2 decimali da 10 90
2. da aggiungere voto in decimali con max 1 decimale ed il range da 1 a 9
3. possibilita di mettere link per cover image 
4. possibilita di aggiungere link per video trailer youtube

**Comment by DarioGiusino** [comment]
Done everythings
